-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  avatar_url text,
  role text default 'user' check (role in ('admin', 'user')),
  created_at timestamp with time zone default now()
);

-- ARTICLES
create table articles (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  description text,
  content_html text, -- For simple articles or preview logic
  price numeric default 0,
  file_path text, -- Path in Supabase Storage (original PDF/Doc)
  preview_path text, -- Path to preview version if needed
  author_id uuid references profiles(id),
  category text,
  is_public boolean default false,
  cover_image text,
  created_at timestamp with time zone default now()
);

-- PURCHASES
create table purchases (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id),
  article_id uuid references articles(id),
  amount_paid numeric not null,
  transaction_id text, -- From Flutterwave
  created_at timestamp with time zone default now()
);

-- RLS POLICIES
alter table profiles enable row level security;
alter table articles enable row level security;
alter table purchases enable row level security;

-- Profiles: Public read, Self update
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);
create policy "New users can insert their profile" on profiles for insert with check (auth.uid() = id);

-- Articles: Public read only if is_public = true. Admins read all.
create policy "Articles are viewable by everyone if public" on articles for select using (is_public = true or auth.uid() in (select id from profiles where role = 'admin'));
create policy "Admins can insert articles" on articles for insert with check (auth.uid() in (select id from profiles where role = 'admin'));
create policy "Admins can update articles" on articles for update using (auth.uid() in (select id from profiles where role = 'admin'));
create policy "Admins can delete articles" on articles for delete using (auth.uid() in (select id from profiles where role = 'admin'));

-- Purchases: Users can see own purchases. Admins see all.
create policy "Users can see own purchases" on purchases for select using (auth.uid() = user_id or auth.uid() in (select id from profiles where role = 'admin'));
create policy "Users can insert purchases (via edge function ideally, but allow for now)" on purchases for insert with check (auth.uid() = user_id);

-- STORAGE BUCKETS
insert into storage.buckets (id, name, public) values ('articles', 'articles', false);
insert into storage.buckets (id, name, public) values ('covers', 'covers', true);

-- Storage Policies
-- Covers: Public read, Admin write
create policy "Covers Public Read" on storage.objects for select using (bucket_id = 'covers');
create policy "Covers Admin Write" on storage.objects for insert with check (bucket_id = 'covers' and auth.uid() in (select id from profiles where role = 'admin'));

-- Articles (Files): 
-- Admin can read/write everything.
-- Users can read IF they purchased the article. (This is complex in SQL alone, usually handled by Signed URLs generated by backend).
-- For now to strictly secure: Only Admin reads directly. Users get usage via Signed Links from App Logic.
create policy "Articles Admin All" on storage.objects for all using (bucket_id = 'articles' and auth.uid() in (select id from profiles where role = 'admin'));

-- FAVOURITES
create table favourites (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade,
  article_id uuid references articles(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(user_id, article_id)
);

-- RLS for Favourites
alter table favourites enable row level security;

-- Policies for Favourites
create policy "Users can view own favourites" on favourites for select using (auth.uid() = user_id);
create policy "Users can add favourites" on favourites for insert with check (auth.uid() = user_id);
create policy "Users can remove favourites" on favourites for delete using (auth.uid() = user_id);

-- MIGRATION: Add author_name to articles for manual entry
-- Run this if you already created the table!
-- alter table articles add column author_name text;
